name: quizlet_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  simple_gradient_text: 1.3.0 # For Decor Text Gradient Color  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1 # For change launcher icon in each platform

flutter_launcher_icons:
  ###
  # If edit in flutter_laucher_icons, run these command in terminal or cmd (In root project dicrectory):
  # > flutter pub run flutter_launcher_icons
  ###
  android: true
  ios: true
  image_path: assets/images/logo.png
  min_sdk_android: 18
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/images/logo.png
  windows:
    generate: true
    image_path: assets/images/win_logo.png
    icon_size: 48         # min:48, max:256, default: 48
  macos:        # uncheck
    generate: true
    image_path: assets/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
  fonts:
    - family: Helvetica-Neue
      fonts:
        - asset: assets/fonts/Choose/HelveticaNeueBold.ttf
